//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AD8495MAX31855Demo {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        /// <summary>The MAX31855Thermocouple module using socket 12 of the mainboard.</summary>
        private Gadgeteer.Modules.Adafruit.MAX31855Thermocouple mAX31855Thermocouple;
        
        /// <summary>The Display N18 module using socket 9 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.DisplayN18 displayN18;
        
        /// <summary>The USB Client SP module using socket 1 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.USBClientSP usbClientSP;
        
        /// <summary>The AD8495Thermocouple module using socket 13 of the mainboard.</summary>
        private Gadgeteer.Modules.Adafruit.AD8495Thermocouple aD8495Thermocouple;
        
        /// <summary>The SD Card module using socket 11 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.SDCard sdCard;
        
        /// <summary>The Button module using socket 5 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Button button;
        
        /// <summary>The MAX31855Thermocouple module using socket 10 of the mainboard.</summary>
        private Gadgeteer.Modules.Adafruit.MAX31855Thermocouple mAX31855Thermocouple2;
        
        /// <summary>This property provides access to the Mainboard API. This is normally not necessary for an end user program.</summary>
        protected new static GHIElectronics.Gadgeteer.FEZReaper Mainboard {
            get {
                return ((GHIElectronics.Gadgeteer.FEZReaper)(Gadgeteer.Program.Mainboard));
            }
            set {
                Gadgeteer.Program.Mainboard = value;
            }
        }
        
        /// <summary>This method runs automatically when the device is powered, and calls ProgramStarted.</summary>
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZReaper();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.mAX31855Thermocouple = new GTM.Adafruit.MAX31855Thermocouple(12);
            this.displayN18 = new GTM.GHIElectronics.DisplayN18(9);
            this.usbClientSP = new GTM.GHIElectronics.USBClientSP(1);
            this.aD8495Thermocouple = new GTM.Adafruit.AD8495Thermocouple(13);
            this.sdCard = new GTM.GHIElectronics.SDCard(11);
            this.button = new GTM.GHIElectronics.Button(5);
            this.mAX31855Thermocouple2 = new GTM.Adafruit.MAX31855Thermocouple(10);
        }
    }
}
